version: "3.9"

services:
  app:
    image: ${DOCKER_IMAGE:-fashionshop-app}:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fashionshop_app
    ports:
      - "8080:80"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT:-3306}
    restart: unless-stopped
